// <auto-generated />
using System;
using DoctorsSchedule.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoctorsSchedule.Migrations
{
    [DbContext(typeof(DoctorsScheduleContext))]
    partial class DoctorsScheduleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DoctorsSchedule.Models.Availability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayId")
                        .HasColumnType("int");

                    b.Property<int>("DocId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("End")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("Start")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.HasIndex("DocId");

                    b.ToTable("Availabilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayId = 2,
                            DocId = 1,
                            End = new TimeSpan(0, 13, 0, 0, 0),
                            Start = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            DayId = 2,
                            DocId = 1,
                            End = new TimeSpan(0, 18, 0, 0, 0),
                            Start = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            DayId = 3,
                            DocId = 1,
                            End = new TimeSpan(0, 13, 0, 0, 0),
                            Start = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            DayId = 3,
                            DocId = 1,
                            End = new TimeSpan(0, 18, 0, 0, 0),
                            Start = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            DayId = 3,
                            DocId = 1,
                            End = new TimeSpan(0, 21, 0, 0, 0),
                            Start = new TimeSpan(0, 20, 0, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            DayId = 4,
                            DocId = 1,
                            End = new TimeSpan(0, 13, 0, 0, 0),
                            Start = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            DayId = 4,
                            DocId = 1,
                            End = new TimeSpan(0, 18, 0, 0, 0),
                            Start = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            DayId = 5,
                            DocId = 1,
                            End = new TimeSpan(0, 18, 0, 0, 0),
                            Start = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            DayId = 6,
                            DocId = 1,
                            End = new TimeSpan(0, 18, 0, 0, 0),
                            Start = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            DayId = 2,
                            DocId = 2,
                            End = new TimeSpan(0, 17, 0, 0, 0),
                            Start = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 11,
                            DayId = 3,
                            DocId = 2,
                            End = new TimeSpan(0, 13, 0, 0, 0),
                            Start = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            DayId = 3,
                            DocId = 2,
                            End = new TimeSpan(0, 21, 0, 0, 0),
                            Start = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 13,
                            DayId = 5,
                            DocId = 2,
                            End = new TimeSpan(0, 18, 0, 0, 0),
                            Start = new TimeSpan(0, 2, 0, 0, 0)
                        },
                        new
                        {
                            Id = 14,
                            DayId = 6,
                            DocId = 2,
                            End = new TimeSpan(0, 13, 0, 0, 0),
                            Start = new TimeSpan(0, 9, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("DoctorsSchedule.Models.Day", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Days");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sunday"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Monday"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tuesday"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Wednesday"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Thursday"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Friday"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Saturday"
                        });
                });

            modelBuilder.Entity("DoctorsSchedule.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mohamed"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ahmed"
                        });
                });

            modelBuilder.Entity("DoctorsSchedule.Models.Availability", b =>
                {
                    b.HasOne("DoctorsSchedule.Models.Day", "Day")
                        .WithMany("Availabilities")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoctorsSchedule.Models.Doctor", "Doctor")
                        .WithMany("Availabilities")
                        .HasForeignKey("DocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("DoctorsSchedule.Models.Day", b =>
                {
                    b.Navigation("Availabilities");
                });

            modelBuilder.Entity("DoctorsSchedule.Models.Doctor", b =>
                {
                    b.Navigation("Availabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
